// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKY3OJuTC0iWpX8OLxCUlnskczd8T-Vog',
    appId: '1:1002748452114:web:6c9c3acc3fa4bc5ba227cb',
    messagingSenderId: '1002748452114',
    projectId: 'product-arena',
    authDomain: 'product-arena.firebaseapp.com',
    storageBucket: 'product-arena.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjFO0UpLMKLY_h2BW9RAVc2zD6qEuKMU',
    appId: '1:1002748452114:android:7293ff742c59def7a227cb',
    messagingSenderId: '1002748452114',
    projectId: 'product-arena',
    storageBucket: 'product-arena.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVWw5LOl_kgGwZKd3oa6ueNp2iCKOZPA',
    appId: '1:1002748452114:ios:bc75320c7da1855ea227cb',
    messagingSenderId: '1002748452114',
    projectId: 'product-arena',
    storageBucket: 'product-arena.appspot.com',
    iosClientId: '1002748452114-rh3s0k0ekplvprkocj0n5c4s5abkpmb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.productArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHVWw5LOl_kgGwZKd3oa6ueNp2iCKOZPA',
    appId: '1:1002748452114:ios:bc75320c7da1855ea227cb',
    messagingSenderId: '1002748452114',
    projectId: 'product-arena',
    storageBucket: 'product-arena.appspot.com',
    iosClientId: '1002748452114-rh3s0k0ekplvprkocj0n5c4s5abkpmb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.productArena',
  );
}
